image: "golang:alpine"
stages:
  - "linter"
  - "build"

linter:
  stage: "linter"
  image: "golangci/golangci-lint:latest-alpine"
  script:
    - "golangci-lint run"

build:
  stage: "build"
  needs:
    - "linter"
  image: "cr.simoncor.net/siempie/go-build:latest"
  script:
    - "GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o gogitlabber cmd/gogitlabber/*"
  artifacts:
    name: "${CI_PROJECT_NAME}"
    paths:
      - "gogitlabber"
