image: "golang:alpine"
stages:
  - "build"

go-build:
  stage: "build"
  image: "cr.simoncor.net/siempie/go-build:latest"
  script:
    - "GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o gogitlabber cmd/gogitlabber/*.go"
  artifacts:
    name: "${CI_PROJECT_NAME}"
    paths:
      - "gogitlabber"
