stages:
  - "linting"
  - "testing"
  - "releasing"

testing:
  stage: "testing"
  needs:
    - "linter"
  image: "cr.simoncor.net/siempie/go-build:latest"
  script:
    - "go test cmd/gogitlabber/*.go"

releasing:
  stage: "releasing"
  needs:
    - "testing"
  image:
    name: "goreleaser/goreleaser:v2.10.2"
    entrypoint: [""]
  rules:
    - if: '$CI_COMMIT_TAG'
  variables:
    GITLAB_TOKEN: '$GORELEASER_GITLAB_TOKEN'
  script:
    - "goreleaser release --clean"


# include jobs
include:

  # linting
  - component: "$CI_SERVER_FQDN/components/golanglint/golanglint@v1.0.0"
