---

stages:
  - "linting"
  - "testing"
  - "releasing"

# include jobs
include:
  - component: "$CI_SERVER_FQDN/components/golang/linting@v2.0.5"
  - component: "$CI_SERVER_FQDN/components/golang/testing@v2.0.5"
  - component: "$CI_SERVER_FQDN/components/golang/releasing@v2.0.5"
