---

stages:
  - "linting"
  - "testing"
  - "releasing"

# include jobs
include:

  # linting
  - component: "$CI_SERVER_FQDN/components/golanglint/golanglint@v1.0.0"

  # testing
  - local: ".gitlab/testing.yaml"

  # releaseing
  - local: ".gitlab/releasing.yaml"
