---
version: 2

# before
before:
  hooks:
    - "go mod tidy"
    - "go generate ./..."

# build
builds:
  - id: "gogitlabber"
    binary: "gogitlabber"
    main: "./cmd/gogitlabber"
    env:
      - "CGO_ENABLED=0"
    goarch:
      - "amd64"
      - "arm64"
    goos:
      - "darwin"
      - "freebsd"
      - "linux"
      - "windows"

# changelog
changelog:
  use: "git"
  sort: "desc"
  groups:
    - title: "🚀 Features"
      regexp: "^feat"
    - title: "🐛 Bug Fixes"
      regexp: "^fix"
    - title: "🛠️ Maintenance"
      regexp: "^(chore|refactor)"
    - title: "🦾 Automation"
      regexp: "^ci"
    - title: "📖 Documentation"
      regexp: "^docs"

# gitlab
gitlab_urls:
  api: "https://gitlab.simoncor.net/api/v4/"
  download: "https://gitlab.simoncor.net"
  use_package_registry: true
