---

clone:
  - name: "clone"
    image: "woodpeckerci/plugin-git"
    settings:
      depth: 0
      tags: true

steps:

  # lintint
  - name: "linting"
    image: "cr.simoncor.net/dockerhub/golangci/golangci-lint:v2.1-alpine"
    commands:
      - "golangci-lint run"

  # testing
  - name: "testing"
    image: "registry.gitlab.simoncor.net/oci/go-build:v25.06.03"
    depends_on:
      - "linting"
    commands:
      - "go test ./..."

  # releasing
  - name: "releasing"
    image: "cr.simoncor.net/dockerhub/goreleaser/goreleaser:v2.10.2"
    depends_on:
      - "testing"
    secrets:
      - "goreleaser_forgejo_token"
    environment:
      FORGEJO_TOKEN:
        from_secret: "goreleaser_forgejo_token"
    commands:
      - "goreleaser release --clean"
    when:
      - event: "tag"
