---

steps:

  - name: "linting"
    image: "cr.simoncor.net/dockerhub/golangci/golangci-lint:v2.12.2-alpine"
    commands:
      - "golangci-lint run"
    when:
      - event:
          - "push"
          - "pull_request"
          - "tag"

  - name: "testing"
    image: "registry.gitlab.simoncor.net/oci/go-build:v25.06.03"
    depends_on:
      - "linting"
    commands:
      - "go test ./..."
    when:
      - event:
          - "push"
          - "pull_request"
          - "tag"

  - name: "releasing"
    image: "cr.simoncor.net/dockerhub/goreleaser/goreleaser:v2.10.2"
    depends_on:
      - "testing"
    environment:
      GITEA_TOKEN:
        from_secret: "goreleaser_forgejo_token"
    commands:
      - "goreleaser release --clean"
    when:
      - event: "tag"
